import React, { useState } from "react";
import { FileText, CalendarDays, RefreshCw, ShieldAlert } from "lucide-react";
import { useIdReport } from "../hooks/api/useReport";
import { KokonutCard } from "./ui/KokonutCard";
import { Badge } from "./ui/Badge";
import { cn } from "../lib/utils";

/**
 * Story 10.2 — Laporan Manajemen (Bahasa Indonesia) view.
 * Renders the rule-based ID management summary generated by the Reporting Engine.
 */

interface ReportViewProps {
  isManagementView: boolean;
}

const PERIOD_OPTIONS = [
  { days: 7, label: "7 Hari" },
  { days: 30, label: "30 Hari" },
];

export const ReportView: React.FC<ReportViewProps> = ({ isManagementView }) => {
  const [days, setDays] = useState<number>(7);
  const { data, isLoading, isError, error, refetch, isFetching } = useIdReport(days);

  return (
    <div className="space-y-6 pb-12">
      <KokonutCard variant="default" className="p-5" interactive={false}>
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 mb-1.5">
              <Badge variant="cyan" size="sm" dot>
                Dual-Language Reporting Engine
              </Badge>
              <span className="text-xs text-slate-600 font-mono font-bold">Bahasa Indonesia · Auto-Generated</span>
            </div>
            <h1 className="text-lg sm:text-xl font-mono font-black text-slate-950 tracking-tight flex items-center gap-2">
              <FileText className="w-5 h-5 text-cyan-600" />
              Laporan Manajemen Operasional
            </h1>
            <p className="text-xs text-slate-600 font-mono mt-0.5 font-semibold">
              Ringkasan otomatis dari data nyata platform (tiket, work item, deployment, audit) — menggantikan pelaporan manual.
            </p>
          </div>

          <div className="flex items-center gap-2 shrink-0">
            {PERIOD_OPTIONS.map((opt) => (
              <button
                key={opt.days}
                onClick={() => setDays(opt.days)}
                className={cn(
                  "px-3 py-1.5 rounded-lg text-xs font-mono font-bold border transition-colors",
                  days === opt.days
                    ? "bg-slate-950 text-white border-slate-950"
                    : "bg-white text-slate-700 border-slate-200 hover:border-slate-400"
                )}
              >
                <CalendarDays className="w-3.5 h-3.5 inline mr-1 -mt-0.5" />
                {opt.label}
              </button>
            ))}
            <button
              onClick={() => refetch()}
              disabled={isFetching}
              className="px-3 py-1.5 rounded-lg text-xs font-mono font-bold border border-slate-200 bg-white text-slate-700 hover:border-slate-400 disabled:opacity-50"
            >
              <RefreshCw className={cn("w-3.5 h-3.5", isFetching && "animate-spin")} />
            </button>
          </div>
        </div>
      </KokonutCard>

      <KokonutCard variant="default" className="p-0 overflow-hidden" interactive={false}>
        <div className="p-4 border-b border-slate-900/20 flex items-center justify-between">
          <span className="text-xs font-mono font-black text-slate-950 uppercase tracking-wider">
            Ringkasan Manajemen (id-ID)
          </span>
          {data && (
            <span className="text-xs font-mono text-slate-600 font-bold">
              Dibuat: {new Date(data.generatedAt).toLocaleString("id-ID")}
            </span>
          )}
        </div>

        <div className="p-5">
          {isLoading && (
            <div className="flex items-center gap-3 text-slate-500 font-mono text-sm py-10 justify-center">
              <RefreshCw className="w-4 h-4 animate-spin" />
              Menyusun laporan dari data operasional…
            </div>
          )}

          {isError && (
            <div className="flex items-start gap-3 rounded-xl border border-red-200 bg-red-50 p-4">
              <ShieldAlert className="w-5 h-5 text-red-600 mt-0.5" />
              <div>
                <p className="text-sm font-bold text-red-900">Laporan gagal dimuat</p>
                <p className="text-xs text-red-700 font-mono mt-0.5">
                  {(error as Error)?.message || "Periksa koneksi Anda atau hak akses (butuh peran Manager ke atas)."}
                </p>
              </div>
            </div>
          )}

          {data && !isLoading && (
            <pre className="whitespace-pre-wrap font-mono text-[13px] leading-relaxed text-slate-800 bg-slate-50 rounded-xl p-5 border border-slate-100">
              {data.report}
            </pre>
          )}
        </div>
      </KokonutCard>
    </div>
  );
};
