export type UserRole =
  | 'Super Admin'
  | 'Organization Admin'
  | 'Manager'
  | 'Project Manager'
  | 'Tech Lead'
  | 'Developer'
  | 'QA'
  | 'Support'
  | 'Viewer';

export type Permission =
  | 'PERM_VIEW_DASHBOARD'
  | 'PERM_VIEW_ENGINEERING'
  | 'PERM_VIEW_MANAGEMENT'
  | 'PERM_WORK_ITEM_CREATE'
  | 'PERM_WORK_ITEM_UPDATE'
  | 'PERM_WORK_ITEM_DELETE'
  | 'PERM_EVIDENCE_ATTACH'
  | 'PERM_TICKET_CREATE'
  | 'PERM_TICKET_UPDATE'
  | 'PERM_TICKET_RESOLVE'
  | 'PERM_INCIDENT_DECLARE'
  | 'PERM_INCIDENT_COMMAND'
  | 'PERM_INCIDENT_RESOLVE'
  | 'PERM_DEPLOYMENT_EXECUTE'
  | 'PERM_DEPLOYMENT_ROLLBACK'
  | 'PERM_AI_SCAN_TRIGGER'
  | 'PERM_AI_TRANSLATE'
  | 'PERM_SERVER_TELEMETRY'
  | 'PERM_AUDIT_LOGS_VIEW'
  | 'PERM_USER_MANAGEMENT';

// Server-authoritative RBAC Permission Matrix (Single Source of Truth)
export const SERVER_ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  'Super Admin': [
    'PERM_VIEW_DASHBOARD',
    'PERM_VIEW_ENGINEERING',
    'PERM_VIEW_MANAGEMENT',
    'PERM_WORK_ITEM_CREATE',
    'PERM_WORK_ITEM_UPDATE',
    'PERM_WORK_ITEM_DELETE',
    'PERM_EVIDENCE_ATTACH',
    'PERM_TICKET_CREATE',
    'PERM_TICKET_UPDATE',
    'PERM_TICKET_RESOLVE',
    'PERM_INCIDENT_DECLARE',
    'PERM_INCIDENT_COMMAND',
    'PERM_INCIDENT_RESOLVE',
    'PERM_DEPLOYMENT_EXECUTE',
    'PERM_DEPLOYMENT_ROLLBACK',
    'PERM_AI_SCAN_TRIGGER',
    'PERM_AI_TRANSLATE',
    'PERM_SERVER_TELEMETRY',
    'PERM_AUDIT_LOGS_VIEW',
    'PERM_USER_MANAGEMENT',
  ],
  'Organization Admin': [
    'PERM_VIEW_DASHBOARD',
    'PERM_VIEW_ENGINEERING',
    'PERM_VIEW_MANAGEMENT',
    'PERM_WORK_ITEM_CREATE',
    'PERM_WORK_ITEM_UPDATE',
    'PERM_WORK_ITEM_DELETE',
    'PERM_EVIDENCE_ATTACH',
    'PERM_TICKET_CREATE',
    'PERM_TICKET_UPDATE',
    'PERM_TICKET_RESOLVE',
    'PERM_INCIDENT_DECLARE',
    'PERM_INCIDENT_COMMAND',
    'PERM_INCIDENT_RESOLVE',
    'PERM_DEPLOYMENT_EXECUTE',
    'PERM_DEPLOYMENT_ROLLBACK',
    'PERM_AI_SCAN_TRIGGER',
    'PERM_AI_TRANSLATE',
    'PERM_SERVER_TELEMETRY',
    'PERM_AUDIT_LOGS_VIEW',
    'PERM_USER_MANAGEMENT',
  ],
  'Tech Lead': [
    'PERM_VIEW_DASHBOARD',
    'PERM_VIEW_ENGINEERING',
    'PERM_VIEW_MANAGEMENT',
    'PERM_WORK_ITEM_CREATE',
    'PERM_WORK_ITEM_UPDATE',
    'PERM_WORK_ITEM_DELETE',
    'PERM_EVIDENCE_ATTACH',
    'PERM_TICKET_CREATE',
    'PERM_TICKET_UPDATE',
    'PERM_TICKET_RESOLVE',
    'PERM_INCIDENT_DECLARE',
    'PERM_INCIDENT_COMMAND',
    'PERM_INCIDENT_RESOLVE',
    'PERM_DEPLOYMENT_EXECUTE',
    'PERM_DEPLOYMENT_ROLLBACK',
    'PERM_AI_SCAN_TRIGGER',
    'PERM_AI_TRANSLATE',
    'PERM_SERVER_TELEMETRY',
    'PERM_AUDIT_LOGS_VIEW',
  ],
  'Project Manager': [
    'PERM_VIEW_DASHBOARD',
    'PERM_VIEW_ENGINEERING',
    'PERM_VIEW_MANAGEMENT',
    'PERM_WORK_ITEM_CREATE',
    'PERM_WORK_ITEM_UPDATE',
    'PERM_EVIDENCE_ATTACH',
    'PERM_TICKET_CREATE',
    'PERM_TICKET_UPDATE',
    'PERM_TICKET_RESOLVE',
    'PERM_INCIDENT_DECLARE',
    'PERM_AI_TRANSLATE',
    'PERM_AUDIT_LOGS_VIEW',
  ],
  'Manager': [
    'PERM_VIEW_DASHBOARD',
    'PERM_VIEW_MANAGEMENT',
    'PERM_TICKET_CREATE',
    'PERM_TICKET_UPDATE',
    'PERM_AI_TRANSLATE',
    'PERM_AUDIT_LOGS_VIEW',
  ],
  'Developer': [
    'PERM_VIEW_DASHBOARD',
    'PERM_VIEW_ENGINEERING',
    'PERM_WORK_ITEM_CREATE',
    'PERM_WORK_ITEM_UPDATE',
    'PERM_EVIDENCE_ATTACH',
    'PERM_TICKET_CREATE',
    'PERM_TICKET_UPDATE',
    'PERM_AI_SCAN_TRIGGER',
    'PERM_SERVER_TELEMETRY',
  ],
  'QA': [
    'PERM_VIEW_DASHBOARD',
    'PERM_VIEW_ENGINEERING',
    'PERM_WORK_ITEM_UPDATE',
    'PERM_EVIDENCE_ATTACH',
    'PERM_TICKET_CREATE',
    'PERM_TICKET_UPDATE',
    'PERM_TICKET_RESOLVE',
  ],
  'Support': [
    'PERM_VIEW_DASHBOARD',
    'PERM_TICKET_CREATE',
    'PERM_TICKET_UPDATE',
  ],
  'Viewer': [
    'PERM_VIEW_DASHBOARD',
  ],
};
